using System;
using System.Collections.Generic;
using System.Text;

namespace NuGet.Common
{
    public interface INuGetError
    {
        /// <summary>
        /// Level to indicate if this is an error or wanring.
        /// </summary>
        LogLevel ErrorLevel { get; set; }

        /// <summary>
        /// Indicates the error code.
        /// </summary>
        NuGetErrorCode ErrorCode { get; set; }

        /// <summary>
        /// Indicates the staring generated by the code to go with the error code.
        /// </summary>
        string ErrorString { get; set; }

        /// <summary>
        /// Indicates the project for which the error was thrown.
        /// </summary>
        string ProjectPath { get; set; }

        /// <summary>
        /// Contains the list of Target Frameworks or Runtime Identifiers for which the error was generated.
        /// </summary>
        List<string> TfmOrRidList { get; set; }

        string ToString();
    }
}
